### PR TITLE
adapt new requirement for reference path

### PR DESCRIPTION
**Pull request by frogcjn**
New requirement ask us to include the extension `d.ts` in reference path.

### CODE REVIEW

**Comment by vitaly-t** [comment]
What new requirement?

Extension `.d.ts` is added by default.

**Comment by frogcjn** [comment]
My VSCode will show red squiggles line under modules and reference sentence. Though it can be compiled with tsc.

**Comment by frogcjn** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/7128#issuecomment-186455129

**Comment by vitaly-t** [comment]
That's a Visual Studio problem. Works in all other systems, as it should.

**Comment by frogcjn** [comment]
Please see https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#1111-source-files-dependencies
there is no automatic adding rule described here.

**Comment by vitaly-t** [comment]
from that link:

> If a source file with extension '.ts' or '.d.ts' corresponding to the reference is located, that file is added as a dependency.

As I said earlier, it works everywhere, except in Visual Studio.

**Comment by frogcjn** [comment]
> If a source file with extension '.ts' or '.d.ts' corresponding to the reference is located, that file is added as a dependency.

It not include extra meaning that tsc will automatically add `.ts` `.d.ts` in your path. It just means path with extension will be added as a dependency.

most search result is full with extension:
https://www.google.co.jp/search?client=safari&rls=en&biw=1440&bih=812&q=%22typings%2Findex%22&oq=%22typings%2Findex%22&gs_l=serp.3...5593.34243.0.34470.5.5.0.0.0.0.784.1830.2-1j6-2.3.0....0...1c.1.64.serp..2.0.0.TzizzBfiGdY

**Pull request closed without merging**
